[tool.poetry]
name = "morpho"
version = "0.2.0"
description = "morpho"
authors = ["mraniki <8766259+mraniki@users.noreply.github.com>"]
license = "MIT License"
readme = "README.md"
packages = [
    { include = "morpho", from = "src" }
]

  
[tool.poetry.urls]
"Changelog" =  "https://github.com/mraniki/morpho/blob/dev/CHANGELOG.rst"
"Support" =  "https://github.com/mraniki/morpho/discussions"
"Issues" =  "https://github.com/mraniki/morpho/issues"

[tool.poetry.dependencies]
python = "^3.10"
dynaconf = "^3.1.12"
loguru = "^0.7.0"
uvicorn = "^0.23.0"
fastapi = "^0.103.1"
playwright = "^1.36.0"
gspread = "^5.10.0"


[tool.poetry.group.test.dependencies]
pytest = "^7.0"
pytest-cov = "^4.1"
pytest-asyncio = "^0.21.0"
pytest-mock = "^3.11.1"
pytest-loguru = "^0.2.0"
pytest-playwright = "^0.4.2"

[tool.poetry.group.dev.dependencies]
python-semantic-release = "^8.0.0"
ruff = "*"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = ">=5,<8"
sphinx_bootstrap_theme = "^0.8.1"
sphinxext-remoteliteralinclude = "^0.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [
  "src"
]

[tool.semantic_release]
upload_to_vcs_release = true
#version_variables = ["pyproject.toml:version"]
version_toml = [
   "pyproject.toml:tool.poetry.version",
   ]
build_command = "pip install poetry && poetry build"
commit_parser = "emoji"

[tool.semantic_release.commit_parser_options]
major_tags = [
    "BREAKING",
    "💥",
    ":boom:",
  ]
minor_tags = ["feat",
    "🥚",":egg:",
    "🚀",":rocket:",
    "💄",":lipstick:",
    "✨",":sparkles:",
]

patch_tags = ["fix","bump","Update",
    "🎨",":art:",
    "🐛",":bug:",
    "🚑",":ambulance:",
    "⚡",":zap:",
    "🔥",":fire:",
    "🚨",":rotating_light:",
    "♻️",":recycle:",
    "🔧",":wrench:",
    "⬆️",":arrow_up:",
    "🩹",":adhesive_bandage:",
    "👷",":construction_worker:",
    "📝",":memo:",
    "🔒",":lock:",
    "👽",":alien:",
    "💬",":speech_balloon:",
    "🥅",":goal_net:",
    "✅",":white_check_mark:",
    "🐳",":whale:",
    "🙈",":see_no_evil:",
    "⚗️",":alembic:",
    "🧐",":monocle_face:",
    "🔇",":mute:",
    "🔊",":volume:",
]

