[default]
loglevel="DEBUG"
host="0.0.0.0"
port="8080"
activeflag="False"
sleeping=6000
#MORPHO_url=""
#MORPHO_check_identifier=""
#MORPHO_check_selector=""
#MORPHO_selector1=""
#MORPHO_selector2=""
#MORPHO_selector3=""
#MORPHO_gsheeturl=""
#MORPHO_activeflag="True"
#MORPHO_credentials=""