name: 🐳 Latest

#on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
on:
  #push:
    #branches: ["main"]
  #pull_request:
  workflow_dispatch:
  workflow_call:
  #schedule:
   #   - cron: '42 23 * * 5'

   
jobs:
  push_to_registry:
    name: 🐳 Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.5.2

      - name: Prepare docker image name
        id: image_names
        run: |
          IMAGES="${GITHUB_REPOSITORY/docker-/},ghcr.io/${GITHUB_REPOSITORY/docker-/}"
          echo "docker_images=$IMAGES" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  
      - name: Log in to the ghcr registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker latest
        id: meta
        uses: docker/metadata-action@v4
        with:
          images:  ${{ env.docker_images }}
          tags: latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          #file: Dockerfile
          file: .registry/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
         
